### ISSUE TITLE
Getting an exception with only requiring and createSimpleLogger()

### ISSUE THREAD

**Issue by shaigi-git** [darrylwest/simple-node-logger#28]
Hi,
I'm experiencing the following issue - just downloaded the tool and tried to use it using the simplest example (didn't even log anything, just required and created it):
```
// create a stdout console logger
const log = require('simple-node-logger').createSimpleLogger();
```
and I'm getting this:
```
[1] module.js:538
[1]     throw err;
[1]     ^
[1]
[1] Error: Cannot find module 'simple-node-logger'
[1]     at Function.Module._resolveFilename (module.js:536:15)
[1]     at Function.Module._load (module.js:466:25)
[1]     at Module.require (module.js:579:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/sgivony/dev/nodeapp3/server/routes/index.js:9:13)
[1]     at Module._compile (module.js:635:30)
[1]     at Object.Module._extensions..js (module.js:646:10)
[1]     at Module.load (module.js:554:32)
[1]     at tryModuleLoad (module.js:497:12)
[1]     at Function.Module._load (module.js:489:3)
[1] [nodemon] app crashed - waiting for file changes before starting...
```
- Node js version is v8.9.3
- I'm running nodemon

Thanks

**Comment by shaigi-git** [comment]
Sorry, my bad. Not an issue.
