### ISSUE TITLE
Issue running latest version

### ISSUE THREAD

**Issue by rmwxiong** [darrylwest/simple-node-logger#29]
```
Error: Cannot find module './test/mocks/MockAppender'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/hododoho/build/node_modules/simple-node-logger/index.js:15:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/hododoho/build/C:/development/reacty/external "simple-node-logger":1:1)
    at __webpack_require__ (/home/hododoho/build/C:/development/reacty/webpack/bootstrap e323131706ee8522505a:25:1)
    at Object.<anonymous> (/home/hododoho/build/server.js:150:77)
    at __webpack_require__ (/home/hododoho/build/C:/development/reacty/webpack/bootstrap e323131706ee8522505a:25:1)
    at Object.<anonymous> (/home/hododoho/build/C:/development/reacty/src/data/sequelize.js:1:1)
    at __webpack_require__ (/home/hododoho/build/C:/development/reacty/webpack/bootstrap e323131706ee8522505a:25:1)
    at Object.<anonymous> (/home/hododoho/build/server.js:3058:69)
    at __webpack_require__ (/home/hododoho/build/C:/development/reacty/webpack/bootstrap e323131706ee8522505a:25:1)
    at Object.<anonymous> (/home/hododoho/build/server.js:2032:72)
    at __webpack_require__ (/home/hododoho/build/C:/development/reacty/webpack/bootstrap e323131706ee8522505a:25:1)
```

**Comment by darrylwest** [comment]
ok, I added a "files" tag to the package.json and tested on another project.  it should be good now...
